apiVersion: v1
kind: Scenario
metadata:
  name: helloworld
spec:
  condition:
  express: eq
    value: P
    operands:
      type: DDS
      name: gear
      value: PowertrainTransmissionCurrentGear
  action: terminate
  target: helloworld