apiVersion: v1
kind: Scenario
metadata:
  name: helloworld
spec:
  condition:
    express: eq
    value: D
    operands:
      type: DDS
      name: gear
      value: PowertrainTransmissionCurrentGear
  action: update
  target: helloworld