# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:20.04 AS gateway-builder
WORKDIR /root

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y libboost-all-dev libssl-dev git cmake gcc g++
COPY ./src/gateway .

WORKDIR /root/gateway_src
RUN mkdir build

WORKDIR /root/gateway_src/build
RUN cmake ../ && \
    make -j$(grep ^processor /proc/cpuinfo | wc -l)


FROM alpine:3.14
RUN apk add gcompat
RUN mkdir -p /root/gateway_src/build && mkdir -p /root/gateway_thirdlib/lib && mkdir -p /lib/x86_64-linux-gnu

COPY --from=gateway-builder /lib64 /lib64
COPY --from=gateway-builder \
    /lib/x86_64-linux-gnu/libpthread.so.0 \
    /lib/x86_64-linux-gnu/libpthread-2.31.so \
    /lib/x86_64-linux-gnu/libstdc++.so.6 \
    /lib/x86_64-linux-gnu/libstdc++.so.6.0.28 \
    /lib/x86_64-linux-gnu/libm.so.6 \
    /lib/x86_64-linux-gnu/libm-2.31.so \
    /lib/x86_64-linux-gnu/libgcc_s.so.1 \
    /lib/x86_64-linux-gnu/libc.so.6 \
    /lib/x86_64-linux-gnu/libc-2.31.so \
    /lib/x86_64-linux-gnu/ld-2.31.so \
    /lib/x86_64-linux-gnu/libssl.so.1.1 \
    /lib/x86_64-linux-gnu/libcrypto.so.1.1 \
    /lib/x86_64-linux-gnu/libdl.so.2 \
    /lib/x86_64-linux-gnu/libdl-2.31.so /lib/x86_64-linux-gnu/
COPY --from=gateway-builder \
    /root/gateway_thirdlib/lib/libddscxx.so.0 \
    /root/gateway_thirdlib/lib/libddscxx.so.0.11.0 \
    /root/gateway_thirdlib/lib/libddsc.so.0 \
    /root/gateway_thirdlib/lib/libddsc.so.0.11.0 \
    /root/gateway_thirdlib/lib/libcpprest.so.2.10 /root/gateway_for_bluechi_thirdlib/lib/ 
COPY --from=gateway-builder /root/gateway_src/build/PiccoloGateway /root/gateway_src/build/

ENTRYPOINT ["/root/gateway_src/build/PiccoloGateway"]

