# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0

FROM pullpiribuilder:latest AS builder

WORKDIR /piccolo
COPY ./src/common/ /piccolo/common
COPY ./src/observer/ /piccolo/observer

WORKDIR /piccolo/observer
RUN cargo build --release


FROM releasealpine:latest
WORKDIR /piccolo

COPY ./src/settings.yaml .

COPY --from=builder \
    /piccolo/observer/target/release/monitoringclient ./

CMD sh
