# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:20.04 AS gateway-builder-arm
WORKDIR /root

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y libboost-all-dev libssl-dev libsystemd-dev git cmake gcc g++
RUN mkdir -p /root/src
COPY ./src/gateway/gateway_src /root/gateway_src
COPY ./src/gateway/gateway_thirdlib_arm /root/gateway_thirdlib

WORKDIR /root/gateway_src
RUN mkdir build

WORKDIR /root/gateway_src/build
RUN cmake ../ && \
    make -j$(grep ^processor /proc/cpuinfo | wc -l)


FROM arm64v8/alpine:3.20
RUN mkdir -p /root/gateway_src/build && mkdir -p /root/gateway_thirdlib/lib && mkdir -p /lib/aarch64-linux-gnu
ENV LD_LIBRARY_PATH /lib/aarch64-linux-gnu

COPY --from=gateway-builder-arm \
    /lib/aarch64-linux-gnu/libc.so.6 \
    /lib/aarch64-linux-gnu/libc-2.31.so \
    /lib/aarch64-linux-gnu/libcrypto.so.1.1 \
    /lib/aarch64-linux-gnu/libdl.so.2 \
    /lib/aarch64-linux-gnu/libdl-2.31.so \
    /lib/aarch64-linux-gnu/libgcc_s.so.1 \
    /lib/aarch64-linux-gnu/libgcrypt.so.20\
    /lib/aarch64-linux-gnu/libgcrypt.so.20.2.5 \
    /lib/aarch64-linux-gnu/libgpg-error.so.0 \
    /lib/aarch64-linux-gnu/libgpg-error.so.0.28.0 \
    /lib/aarch64-linux-gnu/liblz4.so.1 \
    /lib/aarch64-linux-gnu/liblz4.so.1.9.2 \
    /lib/aarch64-linux-gnu/liblzma.so.5 \
    /lib/aarch64-linux-gnu/liblzma.so.5.2.4 \
    /lib/aarch64-linux-gnu/libm.so.6 \
    /lib/aarch64-linux-gnu/libm-2.31.so \
    /lib/aarch64-linux-gnu/libpthread.so.0 \
    /lib/aarch64-linux-gnu/libpthread-2.31.so \
    /lib/aarch64-linux-gnu/librt.so.1 \
    /lib/aarch64-linux-gnu/librt-2.31.so \
    /lib/aarch64-linux-gnu/libssl.so.1.1 \
    /lib/aarch64-linux-gnu/libstdc++.so.6 \
    /lib/aarch64-linux-gnu/libstdc++.so.6.0.28 \
    /lib/aarch64-linux-gnu/libsystemd.so.0 \
    /lib/aarch64-linux-gnu/libsystemd.so.0.28.0 \
    /lib/aarch64-linux-gnu/ld-2.31.so /lib/aarch64-linux-gnu/
COPY --from=gateway-builder-arm \
    /lib/ld-linux-aarch64.so.1 /lib/
COPY --from=gateway-builder-arm \
    /root/gateway_thirdlib/lib/libddscxx.so.0 \
    /root/gateway_thirdlib/lib/libddscxx.so.0.11.0 \
    /root/gateway_thirdlib/lib/libddsc.so.0 \
    /root/gateway_thirdlib/lib/libddsc.so.0.11.0 \
    /root/gateway_thirdlib/lib/libcpprest.so.2.10 /root/gateway_thirdlib/lib/ 
COPY --from=gateway-builder-arm /root/gateway_src/build/PiccoloGateway /root/gateway_src/build/

ENTRYPOINT ["/root/gateway_src/build/PiccoloGateway"]

