# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0

FROM rust:1.78.0-slim AS builder-arm
WORKDIR /piccolo

COPY ./src/Cargo.lock \
     ./src/Cargo.toml /piccolo/
COPY ./src/api /piccolo/api
COPY ./src/api-server/ /piccolo/api-server
COPY ./src/common/ /piccolo/common
COPY ./src/gateway/ /piccolo/gateway
COPY ./src/statemanager/ /piccolo/statemanager
COPY ./src/tools/ /piccolo/tools

RUN apt update -y && \
    apt upgrade -y && \
    apt install -y libdbus-1-dev pkg-config protobuf-compiler && \
    cargo build --release

FROM arm64v8/alpine:3.20
WORKDIR /piccolo

COPY ./piccolo.ini .

COPY --from=builder-arm \
    /piccolo/target/release/api-server \
    /piccolo/target/release/gateway \
    /piccolo/target/release/statemanager \

COPY --from=builder-arm \
    /lib/aarch64-linux-gnu/libc.so.6 \
    /lib/aarch64-linux-gnu/libcap.so.2 \
    /lib/aarch64-linux-gnu/libcap.so.2.66 \
    /lib/aarch64-linux-gnu/libdbus-1.so.3 \
    /lib/aarch64-linux-gnu/libdbus-1.so.3.32.4 \
    /lib/aarch64-linux-gnu/libgcc_s.so.1 \
    /lib/aarch64-linux-gnu/libgcrypt.so.20 \
    /lib/aarch64-linux-gnu/libgcrypt.so.20.4.1 \
    /lib/aarch64-linux-gnu/libgpg-error.so.0 \
    /lib/aarch64-linux-gnu/libgpg-error.so.0.33.1 \
    /lib/aarch64-linux-gnu/liblzma.so.5 \
    /lib/aarch64-linux-gnu/liblzma.so.5.4.1 \
    /lib/aarch64-linux-gnu/liblz4.so.1 \
    /lib/aarch64-linux-gnu/liblz4.so.1.9.4 \
    /lib/aarch64-linux-gnu/libm.so.6 \
    /lib/aarch64-linux-gnu/libsystemd.so.0 \
    /lib/aarch64-linux-gnu/libsystemd.so.0.35.0 \
    /lib/aarch64-linux-gnu/libzstd.so.1 \
    /lib/aarch64-linux-gnu/libzstd.so.1.5.4 \
    /lib/aarch64-linux-gnu/ld-linux-aarch64.so.1 /lib/aarch64-linux-gnu/
COPY --from=builder-arm \
    /lib/ld-linux-aarch64.so.1 /lib/

CMD sh
