# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0

FROM public.ecr.aws/docker/library/rust:1.78.0-slim
WORKDIR /piccolo

COPY ./src/Cargo.lock \
     ./src/Cargo.toml /piccolo/
COPY ./src/api /piccolo/api
COPY ./src/api-server/ /piccolo/api-server
COPY ./src/common/ /piccolo/common
COPY ./src/gateway/ /piccolo/gateway
COPY ./src/importer/ /piccolo/importer
COPY ./src/statemanager/ /piccolo/statemanager
COPY ./src/vendor/ /piccolo/vendor

RUN apt update -y
RUN apt upgrade -y
RUN apt install -y libdbus-1-dev pkg-config protobuf-compiler libssl-dev

RUN cargo build --release

CMD ["sh"]
