# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

# DO NOT USE this file if you can see this comment.

apiVersion: v1
kind: Pod
metadata:
  name: piccolo-server
spec:
  hostNetwork: true
  hostPid: true
  containers:
  - name: rocksdbservice
    image: ghcr.io/mco-piccolo/pullpiri-rocksdb:v11.11.0
    command: ["rocksdbservice", "--path", "/data", "--addr", "0.0.0.0", "--port", "47007"]
    volumeMounts:
    - name: rocksdb-data
      mountPath: /data
    environment:
    - name: RUST_LOG
      value: "info"
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  - name: apiserver
    image: ghcr.io/eclipse-pullpiri/pullpiri:$(VERSION)
    command: ["/piccolo/apiserver"]
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /etc/piccolo/yaml
    - name: config-path
      mountPath: /etc/piccolo/settings.yaml
    environment:
    - name: ROCKSDB_SERVICE_URL
      value: "http://$(HOST_IP):47007"
  - name: policymanager
    image: ghcr.io/eclipse-pullpiri/pullpiri:$(VERSION)
    command: ["/piccolo/policymanager"]
    environment:
    - name: ROCKSDB_SERVICE_URL
      value: "http://$(HOST_IP):47007"
  - name: monitoringserver
    image: ghcr.io/eclipse-pullpiri/pullpiri:$(VERSION)
    command: ["/piccolo/monitoringserver"]
    environment:
    - name: ROCKSDB_SERVICE_URL
      value: "http://$(HOST_IP):47007"
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /etc/piccolo/yaml
    - name: config-path
      mountPath: /etc/piccolo/settings.yaml
  - name: settingsservice
    image: ghcr.io/eclipse-pullpiri/pullpiri:$(VERSION)
    command: ["/piccolo/settingsservice", "--bind-address=$(HOST_IP)", "--bind-port=8080", "--log-level=debug"]
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /etc/piccolo/yaml
    - name: config-path
      mountPath: /etc/piccolo/settings.yaml
    environment:
    - name: ROCKSDB_SERVICE_URL
      value: "http://$(HOST_IP):47007"
  volumes:
  - name: piccolo-yaml
    hostPath:
      path: /etc/piccolo/yaml
  - name: config-path
    hostPath:
      path: /etc/containers/systemd/piccolo/settings.yaml
  - name: rocksdb-data
    hostPath:
      path: /tmp/pullpiri_shared_rocksdb
