# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: piccolo
spec:
  hostNetwork: true
  hostPid: true
  containers:
  - name: api-server
    image: ghcr.io/eclipse-pullpiri/pullpiri:0.1.0
    command: ["/piccolo/api-server"]
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /root/piccolo_yaml
    - name: config-path
      mountPath: /piccolo/settings.yaml
  - name: statemanager
    image: ghcr.io/eclipse-pullpiri/pullpiri:0.1.0
    command: ["/piccolo/statemanager"]
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /root/piccolo_yaml
    - name: dbus
      mountPath: /run/dbus
    - name: systemd
      mountPath: /etc/containers/systemd
    - name: config-path
      mountPath: /piccolo/settings.yaml
  - name: etcd
    image: gcr.io/etcd-development/etcd:v3.5.11
    command: ["/usr/local/bin/etcd"]
    args: ["--data-dir=/etcd-data"]
    volumeMounts:
    - name: etcd-data
      mountPath: /etcd-data
  - name: gateway
    image: ghcr.io/eclipse-pullpiri/pullpiri:0.1.0
    command: ["/piccolo/gateway"]
    env:
    - name: RUST_BACKTRACE
      value: "full"
    volumeMounts:
    - name: config-path
      mountPath: /piccolo/settings.yaml
  volumes:
  - name: piccolo-yaml
    hostPath:
      path: /root/piccolo_yaml
  - name: dbus
    hostPath:
      path: /run/dbus
  - name: systemd
    hostPath:
      path: /etc/containers/systemd
  - name: etcd-data
    hostPath:
      path: /etc/containers/systemd/piccolo/etcd-data
  - name: config-path
    hostPath:
      path: /etc/containers/systemd/piccolo/settings.yaml
