# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: bms-blis
  annotations:
    io.piccolo.annotations.package-type: default
    io.piccolo.annotations.package-name: bms
    io.piccolo.annotations.package-network: default
  labels:
    app: bms-blis
spec:
  hostNetwork: true
  containers:
    - name: blis
      image: localhost/blis:1.0
  terminationGracePeriodSeconds: 0
