# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Scenario
metadata:
  name: helloworld
spec:
  condition: null
  action: terminate
  target: helloworld
---
apiVersion: v1
kind: Package
metadata:
  label: null
  name: helloworld
spec:
  pattern:
    - type: plain
  models:
    - name: helloworld
      node: HPC
      resources:
        volume:
        network:
    - name: helloworld2
      node: HPC
      resources:
        volume:
        network:
---
apiVersion: v1
kind: Model
metadata:
  name: helloworld
spec:
  hostNetwork: true
  containers:
  - name: test-app
    image: docker.io/library/alpine:3.21.3
    command: ["/bin/sh", "-c", "sleep 10000"]
    #args: ["sleep", "10000"]
    workingDir: /app
    stdin: false
    tty: false
    env:
    - name: MY_VAR
      value: "test"
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
#        nvidia.com/gpu: "1"
    securityContext:
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        add: ["NET_ADMIN"]
        drop: ["ALL"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    hostPath:
      path: /host/data
  terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Model
metadata:
  name: helloworld2
spec:
#  hostNetwork: true
  containers:
  - name: test-app2
    image: docker.io/library/alpine:3.21.3
    #command: ["/bin/sh"]
    args: ["sleep", "10000"]
    workingDir: /app
    stdin: false
    tty: false
    ports:
    - containerPort: 8082
      hostPort: 8082
    env:
    - name: MY_VAR
      value: "test2"
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
#        nvidia.com/gpu: "1"
    securityContext:
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    hostPath:
      path: /host/data
  terminationGracePeriodSeconds: 0