apiVersion: v1
kind: Package
metadata:
  label: null
  name: helloworld
spec:
  pattern:
    - type: plain
  models:
    - name: helloworld-core
      node: fvp-rd-kronos
      resources:
        volume: helloworld-volume
        network: helloworld-network